import json
import requests
import os

# --- 1. DIRECTORY SETUP ( create folders if they don't exist) ---
os.makedirs("samples", exist_ok=True)
os.makedirs("output", exist_ok=True)

# EXCLUSIVE FOR TEST ENVIRONMENT - Cisco IOS log creation inside 'samples/'
log_content = """2026-07-26T10:00:01Z %SEC-6-IPACCESSLOGP: list INBOUND_ACL permitted tcp 192.168.1.50(51234) -> 10.10.1.10(80), 1 packet
2026-07-26T10:00:05Z %SEC-6-IPACCESSLOGP: list INBOUND_ACL denied tcp 185.220.101.5(45123) -> 10.10.1.10(22), 1 packet
2026-07-26T10:00:08Z %SEC-6-IPACCESSLOGP: list INBOUND_ACL denied tcp 185.220.101.5(45123) -> 10.10.1.10(22), 1 packet
2026-07-26T10:00:12Z %SEC-6-IPACCESSLOGP: list INBOUND_ACL permitted udp 8.8.8.8(53) -> 10.10.1.20(58432), 1 packet
2026-07-26T10:00:15Z %SEC-6-IPACCESSLOGP: list INBOUND_ACL denied tcp 45.33.32.156(33412) -> 10.10.1.15(3389), 1 packet
2026-07-26T10:00:19Z %SEC-6-IPACCESSLOGP: list INBOUND_ACL denied tcp 185.220.101.5(45123) -> 10.10.1.10(22), 1 packet
2026-07-26T10:00:22Z %SEC-6-IPACCESSLOGP: list INBOUND_ACL denied tcp 185.220.101.5(45123) -> 10.10.1.10(22), 1 packet
2026-07-26T10:00:25Z %SEC-6-IPACCESSLOGP: list INBOUND_ACL denied tcp 45.33.32.156(33412) -> 10.10.1.15(3389), 1 packet
2026-07-26T10:00:31Z %SEC-6-IPACCESSLOGP: list INBOUND_ACL denied tcp 172.16.0.5(12345) -> 10.10.1.10(80), 1 packet
2026-07-26T10:00:35Z %SEC-6-IPACCESSLOGP: list INBOUND_ACL denied tcp 45.33.32.156(33412) -> 10.10.1.15(3389), 1 packet
2026-07-26T10:00:40Z %SEC-6-IPACCESSLOGP: list INBOUND_ACL denied tcp 45.33.32.156(33412) -> 10.10.1.15(3389), 1 packet
2026-07-26T10:00:45Z %SEC-6-IPACCESSLOGP: list INBOUND_ACL permitted tcp 10.0.0.2(44321) -> 10.10.1.50(443), 1 packet
2026-07-26T10:00:50Z %SEC-6-IPACCESSLOGP: list INBOUND_ACL denied tcp 198.51.100.99(60123) -> 10.10.1.10(23), 1 packet
"""

with open("samples/edge_router_syslog.log", "w") as f:
    f.write(log_content.strip() + "\n")

print("[SYSTEM] File samples/edge_router_syslog.log generated successfully!")


def parse_log(file_name):
    ip_list = []
    ip_count = {}

    try:

        with open(file_name, "r") as file:
            for line in file:
                parts = line.split()

                access_action = parts[4]
                if access_action != "denied":
                    continue

                suspicious_ip = parts[6].split("(")[0]

                if suspicious_ip in ip_count:
                    ip_count[suspicious_ip] += 1
                else:
                    ip_count[suspicious_ip] = 1

        for ip, attempts in ip_count.items():
            if attempts > 3:
                ip_list.append(ip)

    except FileNotFoundError:
        return False

    api_headers = {
        "Authorization": "Bearer SOC_NET_TOKEN_9900",
        "User-Agent": "NetEng-ACL-Builder/1.0",
    }

    report_json = []
    critical_ips = []

    for ip in ip_list:
        payload = {"target_ip": ip, "action": "check_reputation"}
        try:
            response = requests.post(
                "https://httpbun.com/post",
                headers=api_headers,
                json=payload,
                timeout=5,
            )
            api_data = response.json()

            target_ip = api_data["json"]["target_ip"]
            first_octet = int(target_ip.split(".")[0])

            if first_octet > 100:
                critical_level = "CRITICAL THREAT"
                critical_ips.append(target_ip)
            else:
                critical_level = "LOW RISK"

            report_json.append(
                {
                    "target_ip": target_ip,
                    "attempts": ip_count[target_ip],
                    "critical_level": critical_level,
                }
            )

        except requests.RequestException:
            print(f"[ERROR] Unable to contact the Threat Intel Server for IP {ip}")

    # --- WRITE JSON REPORT (INSIDE 'output/' FOLDER) ---
    with open("output/threat_reputation_report.json", "w") as json_file:
        json.dump(report_json, json_file, indent=4)

    # --- GENERATE CISCO ACL CONFIGURATION (INSIDE 'output/' FOLDER) ---
    cisco_lines = [
        "! --- AUTOMATED ACL BLOCKLIST GENERATED BY NETSEC FEEDER ---",
        "! Apply to interface facing WAN",
        "ip access-list extended AUTO_THREAT_BLOCK",
    ]

    for blocked_ip in critical_ips:
        cisco_lines.append(f" deny ip host {blocked_ip} any log")

    cisco_lines.append(" permit ip any any")
    cisco_lines.append("! --- END OF CONFIGURATION ---")

    cisco_config = "\n".join(cisco_lines) + "\n"

    with open("output/blocklist_cisco.conf", "w") as conf_file:
        conf_file.write(cisco_config)

    return True


def main():

    log_file = "samples/edge_router_syslog.log"
    parsing_result = parse_log(log_file)

    if not parsing_result:
        print(f"[ERROR] The log file {log_file} does not exist!")
    else:
        print(
            "[SYSTEM] Processing completed! Files generated in the 'output/' directory."
        )


if __name__ == "__main__":
    main()
